routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Centro;

Route::group(['middleware' => ['auth']], function () {
    Route::resource('admin/centros','CentrosController');
    Route::resource('admin/centros/entradas','EntradasController')->except(['index', 'show']);
    Route::resource('admin/centros/proyectos','ProyectosController')->except(['index', 'show','create']);
    Route::get('admin/centros/entradas/{centroId}','EntradasController@index')->name('entradas.index');
    Route::resource('admin/centros/servicios','ServiciosController')->except(['index', 'show']);
    Route::resource('admin/aliados','AliadosController')->except(['show']);
    Route::get('admin/centros/servicios/{centroId}','ServiciosController@index')->name('servicios.index');
    Route::get('admin/centros/proyectos/{centroId}','ProyectosController@index')->name('proyectos.index');
    Route::get('admin/centros/proyectos/create/{centroId}','ProyectosController@create')->name('proyectos.create');
    Route::get('admin/centros/aliados/{centroId}','CentrosController@indexAliados')->name('centros.aliados');
    Route::post('admin/centros/aliados/asociar/{centroId}','CentrosController@asociarAliados')->name('centros.asociarAliados');
    Route::delete('admin/centros/aliados/delete/{centroId}/{id}','CentrosController@borrarAliados')->name('centros.borrarAliados');
    Route::resource('admin/centros/imagenes','ImagenesController')->except(['index', 'show']);
    Route::get('admin/centros/imagenes/{centroId}','ImagenesController@index')->name('imagenes.index');
    Route::resource('admin/centros/horarios','HorariosController')->except(['index', 'show']);
    Route::get('admin/centros/horarios/{centroId}','HorariosController@index')->name('horarios.index');
    Route::delete('admin/centros/audio/{centroId}','CentrosController@destroyAudio')->name('centros.destroyAudio');
});


//Auth::routes();

Route::get('login','Auth\LoginController@showLoginForm')->name('login')->middleware(['guest']);
Route::post('login','Auth\LoginController@login')->middleware(['guest']);
Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::get('centros/subtipos/{tipoId}','CentrosController@getSubtipos');
Route::get('centros/departamentos/{departamentoId}','CentrosController@getMunicipios');
Route::get('get-aliados/{centroId}','CentrosController@getAliados');

/** RUTAS FRONT */
Route::get('/','FrontController@inicio')->name('front.inicio');
Route::get('/centros','FrontController@centros')->name('front.centros');
Route::get('/mapa','FrontController@mapa')->name('front.mapa');
Route::get('/proyectos','FrontController@proyectos')->name('front.proyectos');
Route::post('/proyectos-filter','FrontController@proyectosPartial')->name('front.proyectos.partial');
Route::get('/aliados','FrontController@aliados')->name('front.aliados');
Route::post('/aliados-filter','FrontController@aliadosPartial')->name('front.aliados.partial');
Route::get('/centros/detalles/{centroId}','FrontController@detallesCentro')->name('front.centros.detalles');
Route::get('/centros/detalles/proyecto/{proyectoId}','FrontController@detallesProyecto')->name('front.centros.detalles.proyecto');
Route::get('/filter-centros', 'FrontController@inputCentros');
Route::get('/filter-centros-show/{id}', function ($id){
    $centro = Centro::query()->with('subtipo')->findOrFail($id);
    return response()->json($centro);
});

app/Proyecto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Proyecto extends Model
{
    public function subtipo()
    {
        return $this->hasOne(CentrosCategoria::class,'id','categoria_id');
    }

    public function centro()
    {
        return $this->belongsTo(Centro::class);
    }
    protected $fillable = [
        "nombre",
        "ASCTEL",
        "descripcion",
        "categoria_id",


    ];
}

app/Http/Controllers/ProyectosController.php
<?php

namespace App\Http\Controllers;

use App\Centro;
use App\CentrosCategoria;
use App\Http\Requests\ProyectosRequest;
use App\Proyecto;
use Illuminate\Http\Request;

class ProyectosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($centroId)
    {
        $proyectos = Proyecto::query()->where('centro_id',$centroId)->get();
        $centroNombre = Centro::findOrFail($centroId)->nombre;
        return view('admin.proyectos.index',compact('proyectos','centroNombre', 'centroId'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($centroId)
    {
        $proyectos = Proyecto::query()->where('centro_id',$centroId)->get();
        $centroNombre = Centro::findOrFail($centroId)->nombre;
        $centro = Centro::query()->findOrFail($centroId);
        $categoriasPadre = CentrosCategoria::query()->where('categoria_id',null)->get();
        $categoriasHijas = CentrosCategoria::query()->where('categoria_id',$centro->subtipo->categoria_id)->get();

        return view('admin.proyectos.crear',compact('proyectos','centroNombre','centroId','centroId','centro','categoriasPadre','categoriasHijas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProyectosRequest $request)
    {

        try{

            $proyecto = new Proyecto();
            $proyecto->fill($request->all());
            $proyecto->centro_id = $request->centroId;
            if(!$request->has('ASCTEL')){
                $proyecto->ASCTEL= 0;
            }else{
                $proyecto->ASCTEL= 1;
            }
            $proyecto->save();
            return redirect()->route('proyectos.index',$proyecto->centro_id )->with('success','El proyecto se agregó correctamente.');
        }catch (\Exception $e){
            return redirect()->back()->with('error',$e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $proyecto = Proyecto::query()->findOrFail($id);

        $centro = Centro::query()->findOrFail($proyecto->centro_id);
        $centroId = $centro->id;
        $centroNombre = $centro -> nombre;
        $categoriasPadre = CentrosCategoria::query()->where('categoria_id',null)->get();
        $categoriasHijas = CentrosCategoria::query()->where('categoria_id',$centro->subtipo->categoria_id)->get();

        return view('admin.proyectos.edit',compact('proyecto','centroNombre','centroId','centro','categoriasPadre','categoriasHijas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProyectosRequest $request, $id)
    {
        try{

            $proyecto = Proyecto::findOrFail($id);
            $proyecto->fill($request->all());
            $proyecto->centro_id = $request->centroId;
            if(!$request->has('ASCTEL')){
                $proyecto->ASCTEL= 0;
            }else{
                $proyecto->ASCTEL= 1;
            }
            $proyecto->save();
            return redirect()->route('proyectos.index',$proyecto->centro_id )->with('success','El proyecto se editó correctamente.');
        }catch (\Exception $e){
            return redirect()->back()->with('error',$e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $servicio = Proyecto::findOrFail($id);

            $servicio->delete();
            return redirect()->back()->with('success','El proyecto se eliminó correctamente.');
        }catch (\Exception $e){
            return redirect()->back()->with('error',$e->getMessage());
        }
    }
}

resources/views/admin/proyectos/crear.blade.php
@extends('admin.layout')

@section('styles')
    <link href="{{asset('plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />
    <link href="{{asset('plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')}}" rel="stylesheet" />
@endsection

@section('contenido')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12 d-flex align-items-center">
                <a href="{{route('proyectos.index',$centro->id)}}" class="btn btn-primary btn-sm ">
                    <i class="material-icons">arrow_back</i>
                </a>
                <h2 class="pl-3">Crear proyecto del centro {{$centroNombre}}
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('centros.index')}}"><i class="zmdi zmdi-home"></i> Centros</a></li>
                    <li class="breadcrumb-item active"><a href="{{route('proyectos.index',$centroId)}}">Proyectos del centro {{$centroId}}</a></li>
                    <li class="breadcrumb-item active">Crear</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix justify-content-center">
            <div class="col col-12 col-md-6">
                <div class="card ">
                    <div class="body">
                        @if(session()->has('success'))
                            <div class="alert alert-success" role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger" role="alert">
                                {{session('error')}}
                            </div>
                        @endif
                            @if($errors->has('nombre'))
                                <div class="alert alert-danger" role="alert">
                                    {{$errors->first('nombre')}}
                                </div>
                            @endif
                        <form id="form-store-proyectos" method="post" action="{{route('proyectos.store')}}">
                            @csrf

                            <input type="hidden" name="centroId" value="{{$centroId}}">
                            <label for="nombre">Nombre</label>
                            <input type="text" name="nombre" class="form-control mr-3 mb-3"  placeholder="nombre" id="nombre" required>
                            <label for="descripcion">Descripcion</label>
                            <textarea form="form-store-proyectos" name="descripcion" id="descripcion" class="form-control" rows="3"></textarea>
                            <div class="form-group">
                                <label for="tipo">Tipo</label>
                                <select class="form-control show-tick" id="tipo" name="tipo" onchange="getSubtipos(this)">
                                    @foreach($categoriasPadre as $cP)
                                        <option value="{{$cP->id}}" {{$cP->id === $centro->subtipo->categoria_id ? 'selected' : ''}}>{{$cP->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="subtipo">Subtipo</label>
                                <select class="form-control show-tick" id="subtipo" name="categoria_id">
                                    @foreach($categoriasHijas as $cH)
                                        <option value="{{$cH->id}}" {{$cH->id === $centro->categoria_id ? 'selected' : ''}}>{{$cH->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="checkbox">

                                <input type="checkbox"  name="ASCTEL" id="exampleCheck1">
                                <label for="exampleCheck1">Estrategia Nacional de Apropiación Social de la Ciencia, Tecnología e Innovación (ASCTeI)</label>
                            </div>

                            <button type="button" id="btn-store-proyectos" class="btn btn-primary  btn-sm ml-3">Enviar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('plugins/momentjs/moment.js')}}"></script> <!-- Moment Plugin Js -->
    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{asset('plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js')}}"></script>
    <script>
        $(function () {
            //$('table').DataTable();
            $('#btn-store-proyectos').click(function (e) {
                e.preventDefault();
                cargando();
                $('#form-store-proyectos').trigger('submit')
            })

        });
        function getSubtipos(select) {
            var tipoId = $(select).val()
            $.get('/centros/subtipos/'+tipoId, function (resp) {
                $("#subtipo").empty()

                for(var i=0; i<resp.length; i++){
                    $("#subtipo").append(`<option value="${resp[i].id}">${resp[i].nombre}</option>`)
                }

                $('#subtipo').selectpicker('refresh');

            })
        }
    </script>
@endsection

resources/views/admin/proyectos/edit.blade.php
@extends('admin.layout')

@section('styles')
    <link href="{{asset('plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />
    <link href="{{asset('plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')}}" rel="stylesheet" />
@endsection

@section('contenido')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12 d-flex align-items-center">
                <a href="{{route('proyectos.index',$centro->id)}}" class="btn btn-primary btn-sm ">
                    <i class="material-icons">arrow_back</i>
                </a>
                <h2 class="pl-3">Editar proyecto {{$proyecto->nombre}}
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('centros.index')}}"><i class="zmdi zmdi-home"></i> Centros</a></li>
                    <li class="breadcrumb-item active"><a href="{{route('proyectos.index',$centroId)}}">Proyectos del centro {{$centroId}}</a></li>
                    <li class="breadcrumb-item active">Editar</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix justify-content-center">
            <div class="col col-12 col-md-6">
                <div class="card ">
                    <div class="body">
                        @if(session()->has('success'))
                            <div class="alert alert-success" role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger" role="alert">
                                {{session('error')}}
                            </div>
                        @endif
                            @if($errors->has('nombre'))
                                <div class="alert alert-danger" role="alert">
                                    {{$errors->first('nombre')}}
                                </div>
                            @endif
                        <form action="{{route('proyectos.update',$proyecto->id)}}" id="form-editar-proyectos" method="post" >
                            @csrf
                            @method('PUT')
                            <input type="hidden" name="centroId" value="{{$centroId}}">
                            <label for="nombre">Nombre</label>
                            <input type="text" name="nombre" class="form-control mr-3 mb-3"  placeholder="nombre" id="nombre" required value="{{$proyecto->nombre}}">
                            <label for="descripcion">Descripcion</label>
                            <textarea name="descripcion" class="form-control" rows="3" >{{$proyecto->descripcion}}</textarea>
                            <div class="form-group">
                                <label for="tipo">Tipo</label>
                                <select class="form-control show-tick" id="tipo" name="tipo" onchange="getSubtipos(this)">
                                    @foreach($categoriasPadre as $cP)
                                        <option value="{{$cP->id}}" {{$cP->id === $proyecto->subtipo->categoria_id ? 'selected' : ''}} >{{$cP->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="subtipo">Subtipo</label>
                                <select class="form-control show-tick" id="subtipo" name="categoria_id">
                                    @foreach($categoriasHijas as $cH)
                                        <option value="{{$cH->id}}" {{$cH->id === $proyecto->categoria_id ? 'selected' : ''}}>{{$cH->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="checkbox">

                                <input type="checkbox"  name="ASCTEL" id="exampleCheck1" {{$proyecto->ASCTEL === 1 ? 'checked' : ''}}>
                                <label for="exampleCheck1">Estrategia Nacional de Apropiación Social de la Ciencia, Tecnología e Innovación (ASCTeI)</label>
                            </div>

                            <button type="button" id="btn-editar-proyectos" class="btn btn-primary  btn-sm ml-3">Enviar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('plugins/momentjs/moment.js')}}"></script> <!-- Moment Plugin Js -->
    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{asset('plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js')}}"></script>
    <script>
        $(function () {
            //$('table').DataTable();
            $('#btn-editar-proyectos').click(function (e) {
                e.preventDefault();
                cargando();
                $('#form-editar-proyectos').trigger('submit')
            })

        });
        function getSubtipos(select) {
            var tipoId = $(select).val()
            $.get('/centros/subtipos/'+tipoId, function (resp) {
                $("#subtipo").empty()

                for(var i=0; i<resp.length; i++){
                    $("#subtipo").append(`<option value="${resp[i].id}">${resp[i].nombre}</option>`)
                }

                $('#subtipo').selectpicker('refresh');

            })
        }
    </script>
@endsection

resources/views/admin/proyectos/index.blade.php
@extends('admin.layout')

@section('styles')
    <link rel="stylesheet" href="{{asset('plugins/jquery-datatable/dataTables.bootstrap4.min.css')}}">
    <style>
        .tr-editable p{
            display: none;
        }
        .tr-editable input{
            display: block !important;
        }

        .tr-editable .boton-enviar{
            display: block !important;
        }
        .tr-editable .botones-normales{
            display: none;
        }
    </style>
@endsection

@section('contenido')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12 d-flex align-items-center">
                <a href="{{route('centros.index')}}" class="btn btn-primary btn-sm ">
                    <i class="material-icons">arrow_back</i>
                </a>
                <h2 class="pl-3">Proyectos del centro {{$centroNombre}}
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('centros.index')}}"><i class="zmdi zmdi-home"></i> Centros</a></li>
                    <li class="breadcrumb-item active">Proyectos del centro {{$centroId}}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix justify-content-center">
            <div class="col col-12 col-md-8">
                <div class="card ">
                    <div class="body">


                        @if(session()->has('success'))
                            <div class="alert alert-success" role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger" role="alert">
                                {{session('error')}}
                            </div>
                        @endif

                            <div class = "row justify-content-end">
                                <a href="{{route('proyectos.create',$centroId)}}" class="btn btn-primary btn-sm ">
                                    <i class="material-icons">add_circle</i>
                                    <span style="vertical-align: top" class="d-inline-block pt-1">Agregar Proyecto</span>
                                </a></div>
                        <table class="table table-hover table-striped table-borderless m-b-0" id="table-centros">
                            <thead>
                            <tr>

                                <th>Nombre</th>
                                <th>Acciones</th>

                            </tr>
                            </thead>
                            <tbody class="no-border-x">
                            @foreach($proyectos as $proyecto)
                                <tr>

                                    <td>
                                        <p>{{$proyecto->nombre}}</p>
                                    </td>

                                    <td>
                                        <div class="botones-normales">
                                            <div class="btn-group">
                                                <a href="{{route('proyectos.edit',$proyecto->id)}}" class="btn btn-primary btn-sm">
                                                    <i class="material-icons">edit</i>
                                                </a>
                                                <button onclick="eliminarEntrada('{{$proyecto->id}}')" class="btn btn-danger btn-sm">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                            </div>

                                        </div>

                                        <form id="form-entrada-{{$proyecto->id}}" action="{{route('proyectos.destroy',$proyecto->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')

    <script>
        $(function () {
            $('table').DataTable();
        });

        function eliminarEntrada(id) {
            swal({
                title:'¿Estás seguro?',
                text:'¿Deseas eliminar este proyecto?',
                type:'warning',
                showCancelButton: true,
                cancelButtonText:
                    'Cancelar',
            }).then(()=>{
                cargando()
                $("#form-entrada-"+id).trigger('submit')
            });
        }




    </script>
@endsection