routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Centro;

Route::group(['middleware' => ['auth']], function () {
    Route::resource('admin/centros','CentrosController');
    Route::resource('admin/centros/entradas','EntradasController')->except(['index', 'show']);
    Route::resource('admin/centros/proyectos','ProyectosController')->except(['index', 'show','create']);
    Route::get('admin/centros/entradas/{centroId}','EntradasController@index')->name('entradas.index');
    Route::resource('admin/centros/servicios','ServiciosController')->except(['index', 'show']);
    Route::resource('admin/aliados','AliadosController')->except(['show']);
    Route::get('admin/centros/servicios/{centroId}','ServiciosController@index')->name('servicios.index');
    Route::get('admin/centros/proyectos/{centroId}','ProyectosController@index')->name('proyectos.index');
    Route::get('admin/centros/proyectos/create/{centroId}','ProyectosController@create')->name('proyectos.create');
    Route::get('admin/centros/aliados/{centroId}','CentrosController@indexAliados')->name('centros.aliados');
    Route::post('admin/centros/aliados/asociar/{centroId}','CentrosController@asociarAliados')->name('centros.asociarAliados');
    Route::delete('admin/centros/aliados/delete/{centroId}/{id}','CentrosController@borrarAliados')->name('centros.borrarAliados');
    Route::resource('admin/centros/imagenes','ImagenesController')->except(['index', 'show']);
    Route::get('admin/centros/imagenes/{centroId}','ImagenesController@index')->name('imagenes.index');
    Route::resource('admin/centros/horarios','HorariosController')->except(['index', 'show']);
    Route::get('admin/centros/horarios/{centroId}','HorariosController@index')->name('horarios.index');
    Route::delete('admin/centros/audio/{centroId}','CentrosController@destroyAudio')->name('centros.destroyAudio');
});


//Auth::routes();

Route::get('login','Auth\LoginController@showLoginForm')->name('login')->middleware(['guest']);
Route::post('login','Auth\LoginController@login')->middleware(['guest']);
Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::get('centros/subtipos/{tipoId}','CentrosController@getSubtipos');
Route::get('centros/departamentos/{departamentoId}','CentrosController@getMunicipios');
Route::get('get-aliados/{centroId}','CentrosController@getAliados');

/** RUTAS FRONT */
Route::get('/','FrontController@inicio')->name('front.inicio');
Route::get('/centros','FrontController@centros')->name('front.centros');
Route::get('/mapa','FrontController@mapa')->name('front.mapa');
Route::get('/proyectos','FrontController@proyectos')->name('front.proyectos');
Route::post('/proyectos-filter','FrontController@proyectosPartial')->name('front.proyectos.partial');
Route::get('/aliados','FrontController@aliados')->name('front.aliados');
Route::post('/aliados-filter','FrontController@aliadosPartial')->name('front.aliados.partial');
Route::get('/centros/detalles/{centroId}','FrontController@detallesCentro')->name('front.centros.detalles');
Route::get('/centros/detalles/proyecto/{proyectoId}','FrontController@detallesProyecto')->name('front.centros.detalles.proyecto');
Route::get('/filter-centros', 'FrontController@inputCentros');
Route::get('/filter-centros-show/{id}', function ($id){
    $centro = Centro::query()->with('subtipo')->findOrFail($id);
    return response()->json($centro);
});

resources/views/admin/aliados.blade.php
@extends('admin.layout')

@section('styles')
    <link rel="stylesheet" href="{{asset('plugins/jquery-datatable/dataTables.bootstrap4.min.css')}}">
    <style>
        .tr-editable p{
            display: none;
        }
        .tr-editable input{
            display: block !important;
            width: 80%;
        }

        .tr-editable .boton-enviar{
            display: block !important;
        }
        .tr-editable .botones-normales{
            display: none;
        }
    </style>
@endsection

@section('contenido')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12 d-flex align-items-center">
                <a href="{{route('centros.index')}}" class="btn btn-primary btn-sm ">
                    <i class="material-icons">arrow_back</i>
                </a>
                <h2 class="pl-3">Aliados
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('centros.index')}}"><i class="zmdi zmdi-home"></i> Centros</a></li>
                    <li class="breadcrumb-item active">Aliados</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix justify-content-center">
            <div class="col col-12 col-md-8">
                <div class="card ">
                    <div class="body">
                        @if(session()->has('success'))
                            <div class="alert alert-success" role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger" role="alert">
                                {{session('error')}}
                            </div>
                        @endif
                        <p class="text-danger">{{$errors->first('nombre')}}</p>
                        <p class="text-danger">{{$errors->first('nombre_edit')}}</p>
                        <p class="text-danger">{{$errors->first('url')}}</p>
                        <p class="text-danger">{{$errors->first('url_edit')}}</p>
                        <form class="form" id="form-store-aliadosGeneral" method="post" action="{{route('aliados.store')}}">
                            @csrf
                                <div class="row">
                                    <div class="col-4 pt-1">
                                        <input type="text" name="nombre" class="form-control mr-3"  placeholder="Nombre" required>
                                    </div>
                                    <div class="col-4 pt-1">
                                        <input type="text" name="url" class="form-control" placeholder="URL" required>
                                    </div>
                                    <div class="col-3">
                                        <button id="btn-store-aliadosGeneral" type="button" class="btn btn-primary btn-block btn-sm ml-3">Enviar</button>
                                    </div>
                                </div>




                        </form>
                            </div>
                    </div>
                <div class="card ">
                    <div class="body">
                        <table class="table table-hover table-striped table-borderless m-b-0" id="table-centros">
                            <thead>
                            <tr>

                                <th>Nombre</th>
                                <th>URL</th>
                                <th>Acciones</th>


                            </tr>
                            </thead>
                            <tbody class="no-border-x">
                            @foreach($aliados as $aliado)
                                <tr>

                                    <td>
                                        <p>{{$aliado->nombre}}</p>
                                        <input  type="text" name="nuevoNombre" class="form-control bg-white" value="{{$aliado->nombre}}" style="display: none">
                                    </td>

                                    <td>
                                        <p>{{$aliado->url}}</p>
                                        <input  type="text" name="nuevoURL" class="form-control bg-white" value="{{$aliado->url}}" style="display: none">
                                    </td>
                                    <td>
                                        <div class="botones-normales">
                                            <div class="btn-group">
                                                <button onclick="mostrarInputs(this)" class="btn btn-primary btn-sm">
                                                    <i class="material-icons">edit</i>
                                                </button>
                                                <button onclick="eliminarEntrada('{{$aliado->id}}')" class="btn btn-danger btn-sm">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                            </div>
                                        </div>
                                        <button onclick="updateEntrada('{{$aliado->id}}')" class="btn btn-success btn-sm boton-enviar" style="display: none">
                                            <i style="font-size: 16px" class="material-icons">check_circle</i>
                                        </button>
                                        <form id="form-entrada-{{$aliado->id}}" action="{{route('aliados.destroy',$aliado->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <form id="form-editar-{{$aliado->id}}" action="{{route('aliados.update',$aliado->id)}}" method="post">
                                            @csrf
                                            <input type="hidden" name="nombre_edit">
                                            <input type="hidden" name="url_edit">
                                            @method('PUT')
                                        </form>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('bundles/datatablescripts.bundle.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.html5.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.print.min.js')}}"></script>
    <script>
        $(function () {
            $('table').DataTable();
            $('#btn-store-aliadosGeneral').click(function (e) {
                e.preventDefault();
                cargando();
                $('#form-store-aliadosGeneral').trigger('submit')
            })
        });

        function eliminarEntrada(id) {
            swal({
                title:'¿Estás seguro?',
                text:'¿Deseas eliminar este aliado?',
                type:'warning',
                showCancelButton: true,
                cancelButtonText:
                    'Cancelar',
            }).then(()=>{
                cargando()
                $("#form-entrada-"+id).trigger('submit')
            });
        }

        function updateEntrada(id) {
            cargando()
            var formSelector  = "#form-editar-"
            $("input[name='nombre_edit']").val($("input[name='nuevoNombre']").val());
            $("input[name='url_edit']").val($("input[name='nuevoURL']").val());
            $(formSelector+id).trigger('submit')

        }

        function mostrarInputs(button) {
            var tr = $(button).closest('tr')
            tr.addClass('tr-editable')
        }
    </script>
@endsection

resources/views/admin/entradas.blade.php
@extends('admin.layout')

@section('styles')
    <link rel="stylesheet" href="{{asset('plugins/jquery-datatable/dataTables.bootstrap4.min.css')}}">
    <style>
        .tr-editable p{
            display: none;
        }
        .tr-editable input{
            display: block !important;
        }

        .tr-editable .boton-enviar{
            display: block !important;
        }
        .tr-editable .botones-normales{
            display: none;
        }
    </style>
@endsection

@section('contenido')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12 d-flex align-items-center">
                <a href="{{route('centros.index')}}" class="btn btn-primary btn-sm ">
                    <i class="material-icons">arrow_back</i>
                </a>
                <h2 class="pl-3">Entradas del centro {{$centroNombre}}
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('centros.index')}}"><i class="zmdi zmdi-home"></i> Centros</a></li>
                    <li class="breadcrumb-item active">Entradas del centro {{$centroId}}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix justify-content-center">
            <div class="col col-12 col-md-8">
                <div class="card ">
                    <div class="body">
                        @if(session()->has('success'))
                            <div class="alert alert-success" role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger" role="alert">
                                {{session('error')}}
                            </div>
                        @endif
                            <p class="text-danger">{{$errors->first('nombre')}}</p>
                            <p class="text-danger">{{$errors->first('nombre_edit')}}</p>
                            <p class="text-danger">{{$errors->first('valor')}}</p>
                            <p class="text-danger">{{$errors->first('valor_edit')}}</p>

                        <form method="post" action="{{route('entradas.store')}}" id="form-store-entradas">
                            @csrf

                                <div class="row">
                                    <div class="col-4 pt-1">
                                        <input type="number" name="valor"  class="form-control mr-3"  placeholder="Valor">
                                    </div>
                                    <div class="col-4 pt-1">
                                        <input type="text" name="nombre" class="form-control" placeholder="Nombre" required>
                                    </div>
                                    <div class="col-4">
                                        <button type="button" id="btn-store-entradas" class="btn btn-primary  btn-sm btn-block">Enviar</button>
                                    </div>
                                </div>







                            <input type="hidden" name="centroId" value="{{$centroId}}">
                        </form>
                            </div>
                    </div>
                <div class="card ">
                    <div class="body">
                        <table class="table table-hover table-striped table-borderless m-b-0" id="table-centros">
                            <thead>
                            <tr>

                                <th>Valor</th>
                                <th>Nombre</th>
                                <th>Acciones</th>


                            </tr>
                            </thead>
                            <tbody class="no-border-x">
                            @foreach($entradas as $entrada)
                                <tr>

                                    <td>

                                        <p class="money">${{number_format($entrada->valor,0,",",".")}}</p>
                                        <input type="number" id="nuevoValor-{{$entrada->id}}" class="form-control bg-white" value="{{$entrada->valor}}" style="display: none">
                                    </td>

                                    <td>
                                        <p>{{$entrada->nombre}}</p>
                                        <input id="nuevoNombre-{{$entrada->id}}" class="form-control bg-white" value="{{$entrada->nombre}}" style="display: none">
                                    </td>
                                    <td>
                                        <div class="botones-normales">
                                            <div class="btn-group">
                                                <button onclick="mostrarInputs(this)" class="btn btn-primary btn-sm">
                                                    <i class="material-icons">edit</i>
                                                </button>
                                                <button onclick="eliminarEntrada('{{$entrada->id}}')" class="btn btn-danger btn-sm">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                            </div>

                                        </div>
                                        <button onclick="updateEntrada('{{$entrada->id}}')" class="btn btn-success btn-sm boton-enviar" style="display: none">
                                            <i style="font-size: 16px" class="material-icons">check_circle</i>
                                        </button>

                                        <form id="form-entrada-{{$entrada->id}}" action="{{route('entradas.destroy',$entrada->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <form id="form-editar-{{$entrada->id}}" action="{{route('entradas.update',$entrada->id)}}" method="post">
                                            @csrf
                                            <input type="hidden" name="valor_edit">
                                            <input type="hidden" name="nombre_edit">
                                            @method('PUT')
                                        </form>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('bundles/datatablescripts.bundle.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.html5.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.print.min.js')}}"></script>

    <script>
        $(function () {
            //$('table').DataTable();
            $('#btn-store-entradas').click(function (e) {
                e.preventDefault();
                cargando();
                $('#form-store-entradas').trigger('submit')
            })

        });

        function eliminarEntrada(id) {
            swal({
                title:'¿Estás seguro?',
                text:'¿Deseas eliminar esta entrada?',
                type:'warning',
                showCancelButton: true,
                cancelButtonText:
                    'Cancelar',
            }).then(()=> {
                cargando()
                $("#form-entrada-"+id).trigger('submit')
            });
        }

        function updateEntrada(id) {
            cargando()
            var formSelector  = "#form-editar-"
            var nuevoNombre= "#nuevoNombre-"+id
            var nuevoValor = "#nuevoValor-"+id
            $("input[name='valor_edit']").val($(nuevoValor).val());
            $("input[name='nombre_edit']").val($(nuevoNombre).val());
            $(formSelector+id).trigger('submit')

        }

        function mostrarInputs(button) {
            var tr = $(button).closest('tr')
            tr.addClass('tr-editable')
        }


    </script>
@endsection

resources/views/admin/horarios.blade.php
@extends('admin.layout')

@section('styles')
    <link rel="stylesheet" href="{{asset('plugins/jquery-datatable/dataTables.bootstrap4.min.css')}}">
    <style>
        .tr-editable p{
            display: none;
        }
        .tr-editable input{
            display: block !important;
        }

        .tr-editable .boton-enviar{
            display: block !important;
        }
        .tr-editable .botones-normales{
            display: none;
        }
    </style>
@endsection

@section('contenido')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12 d-flex align-items-center">
                <a href="{{route('centros.index')}}" class="btn btn-primary btn-sm ">
                    <i class="material-icons">arrow_back</i>
                </a>
                <h2 class="pl-3">Horarios del centro {{$centroNombre}}
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('centros.index')}}"><i class="zmdi zmdi-home"></i> Centros</a></li>
                    <li class="breadcrumb-item active">Horarios del centro {{$centroId}}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix justify-content-center">
            <div class="col col-12 col-md-8">
                <div class="card ">
                    <div class="body">
                        @if(session()->has('success'))
                            <div class="alert alert-success" role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger" role="alert">
                                {{session('error')}}
                            </div>
                        @endif
                        <p class="text-danger">{{$errors->first('horario')}}</p>
                        <p class="text-danger">{{$errors->first('horario_edit')}}</p>

                        <form id="form-store-horarios" method="post" action="{{route('horarios.store')}}">
                            @csrf
                            <input type="hidden" name="centroId" value="{{$centroId}}">

                            <div class="row">
                                <div class="col-8 pt-1">
                                    <input type="text" name="horario" class="form-control mr-3"  placeholder="Ej: Todos los días, de 9:00 a. m. a 4:30 p. m." required>
                                </div>
                                <div class="col-4">
                                    <button type="button" id="btn-store-horarios" class="btn btn-primary  btn-sm ml-3 btn-block">Enviar</button>
                                </div>
                            </div>


                        </form>
                            </div>
                    </div>
                <div class="card ">
                    <div class="body">
                        <table class="table table-hover table-striped table-borderless m-b-0" id="table-centros">
                            <thead>
                            <tr>

                                <th>Dias</th>
                                <th>Acciones</th>


                            </tr>
                            </thead>
                            <tbody class="no-border-x">

                            @foreach($horarios as $horario)
                                <tr>

                                    <td>
                                        <p>{{$horario->horario}}</p>
                                        <input id="nuevoHorario-{{$horario->id}}" class="form-control bg-white" value="{{$horario->horario}}" style="display: none">
                                    </td>

                                    <td>
                                        <div class="botones-normales">
                                            <div class="btn-group">
                                                <button onclick="mostrarInputs(this)" class="btn btn-primary btn-sm">
                                                    <i class="material-icons">edit</i>
                                                </button>
                                                <button onclick="eliminarEntrada('{{$horario->id}}')" class="btn btn-danger btn-sm">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                            </div>

                                        </div>
                                        <button onclick="updateEntrada('{{$horario->id}}')" class="btn btn-success btn-sm boton-enviar" style="display: none">
                                            <i style="font-size: 16px"  class="material-icons">check_circle</i>
                                        </button>
                                        <form id="form-entrada-{{$horario->id}}" action="{{route('horarios.destroy',$horario->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <form id="form-editar-{{$horario->id}}" action="{{route('horarios.update',$horario->id)}}" method="post">
                                            @csrf
                                            <input type="hidden" name="horario_edit">
                                            @method('PUT')
                                        </form>
                                    </td>

                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('bundles/datatablescripts.bundle.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.html5.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.print.min.js')}}"></script>
    <script>
        $(function () {
            //$('table').DataTable();
            $('#btn-store-horarios').click(function (e) {
                e.preventDefault();
                cargando();
                $('#form-store-horarios').trigger('submit')
            })

        });

        function eliminarEntrada(id) {
            swal({
                title:'¿Estás seguro?',
                text:'¿Deseas eliminar este horario?',
                type:'warning',
                showCancelButton: true,
                cancelButtonText:
                    'Cancelar',
            }).then(()=>{
                cargando()
                $("#form-entrada-"+id).trigger('submit')
            });
        }

        function updateEntrada(id) {
            cargando()
            var formSelector  = "#form-editar-";
            var horarioSeleccionado = "#nuevoHorario-"+id;
            $("input[name='horario_edit']").val($(horarioSeleccionado).val());
            $(formSelector+id).trigger('submit')

        }

        function mostrarInputs(button) {
            var tr = $(button).closest('tr')
            tr.addClass('tr-editable')
        }
    </script>
@endsection