routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Centro;

Route::group(['middleware' => ['auth']], function () {
    Route::resource('admin/centros','CentrosController');
    Route::resource('admin/centros/entradas','EntradasController')->except(['index', 'show']);
    Route::resource('admin/centros/proyectos','ProyectosController')->except(['index', 'show','create']);
    Route::get('admin/centros/entradas/{centroId}','EntradasController@index')->name('entradas.index');
    Route::resource('admin/centros/servicios','ServiciosController')->except(['index', 'show']);
    Route::resource('admin/aliados','AliadosController')->except(['show']);
    Route::get('admin/centros/servicios/{centroId}','ServiciosController@index')->name('servicios.index');
    Route::get('admin/centros/proyectos/{centroId}','ProyectosController@index')->name('proyectos.index');
    Route::get('admin/centros/proyectos/create/{centroId}','ProyectosController@create')->name('proyectos.create');
    Route::get('admin/centros/aliados/{centroId}','CentrosController@indexAliados')->name('centros.aliados');
    Route::post('admin/centros/aliados/asociar/{centroId}','CentrosController@asociarAliados')->name('centros.asociarAliados');
    Route::delete('admin/centros/aliados/delete/{centroId}/{id}','CentrosController@borrarAliados')->name('centros.borrarAliados');
    Route::resource('admin/centros/imagenes','ImagenesController')->except(['index', 'show']);
    Route::get('admin/centros/imagenes/{centroId}','ImagenesController@index')->name('imagenes.index');
    Route::resource('admin/centros/horarios','HorariosController')->except(['index', 'show']);
    Route::get('admin/centros/horarios/{centroId}','HorariosController@index')->name('horarios.index');
    Route::delete('admin/centros/audio/{centroId}','CentrosController@destroyAudio')->name('centros.destroyAudio');
});


//Auth::routes();

Route::get('login','Auth\LoginController@showLoginForm')->name('login')->middleware(['guest']);
Route::post('login','Auth\LoginController@login')->middleware(['guest']);
Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::get('centros/subtipos/{tipoId}','CentrosController@getSubtipos');
Route::get('centros/departamentos/{departamentoId}','CentrosController@getMunicipios');
Route::get('get-aliados/{centroId}','CentrosController@getAliados');

/** RUTAS FRONT */
Route::get('/','FrontController@inicio')->name('front.inicio');
Route::get('/centros','FrontController@centros')->name('front.centros');
Route::get('/mapa','FrontController@mapa')->name('front.mapa');
Route::get('/proyectos','FrontController@proyectos')->name('front.proyectos');
Route::post('/proyectos-filter','FrontController@proyectosPartial')->name('front.proyectos.partial');
Route::get('/aliados','FrontController@aliados')->name('front.aliados');
Route::post('/aliados-filter','FrontController@aliadosPartial')->name('front.aliados.partial');
Route::get('/centros/detalles/{centroId}','FrontController@detallesCentro')->name('front.centros.detalles');
Route::get('/centros/detalles/proyecto/{proyectoId}','FrontController@detallesProyecto')->name('front.centros.detalles.proyecto');
Route::get('/filter-centros', 'FrontController@inputCentros');
Route::get('/filter-centros-show/{id}', function ($id){
    $centro = Centro::query()->with('subtipo')->findOrFail($id);
    return response()->json($centro);
});

app/Centro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Centro extends Model
{
    protected $fillable = [
        "nombre",
        "categoria_id",
        "owner",
        "descripcion",
        "direccion",
        "latitud",
        "longitud",
        "pagina_web",
        "correo",
        "telefono",
        "celular",
        "fecha_creacion",
        "departamento_codigo",
        "municipio_codigo",
    ];

    public function subtipo()
    {
        return $this->hasOne(CentrosCategoria::class,'id','categoria_id');
    }

    public function departamento()
    {
        return $this->hasOne(Departamento::class,'codigo','departamento_codigo');
    }

    public function municipio()
    {
        return $this->hasOne(Municipio::class,'codigo','municipio_codigo');
    }

    public function proyectos()
    {
        return $this->hasMany(Proyecto::class);
    }

    public function aliados(){
        return $this->belongsToMany(Aliado::class);
    }

    public function servicios()
    {
        return $this->hasMany(CentrosServicio::class);
    }

    public function entradas()
    {
        return $this->hasMany(CentrosEntrada::class);
    }

    public function horarios()
    {
        return $this->hasMany(CentrosHorario::class);
    }

    public function imagenes()
    {
        return $this->hasMany(CentroImage::class);
    }


}

app/Http/Controllers/CentrosController.php
<?php

namespace App\Http\Controllers;

use App\Aliado;
use App\Centro;
use App\CentrosCategoria;
use App\Departamento;
use App\Globals\CodesResponse;
use App\Globals\Response;
use App\Http\Requests\CentroRequest;
use App\Municipio;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class CentrosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $centros = Centro::with('subtipo','municipio')->get();
        return view('admin.centros.index', compact('centros'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departamentos = Departamento::query()->orderBy('descripcion')->get();
        $categoriasPadre = CentrosCategoria::query()->where('categoria_id',null)->get();
        $categoriasHijas = CentrosCategoria::query()->where('categoria_id', !null)->get();

        return view('admin.centros.create',compact('categoriasPadre','categoriasHijas','departamentos'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CentroRequest $request)
    {
        try{
            $centro = new Centro();
            $centro->fill($request->all());
            if(intval($request->departamento_codigo)===8 || intval($request->departamento_codigo)===5){
                $centro->departamento_codigo = '0'.$request->departamento_codigo;
            }
            if($request->has('audio')){
                $audio = Storage::put('public',$request->audio);
                $centro->audio = $audio;

            }
            $centro->save();
            return Response::responseSuccess('Bien! El centro se creó correctamente',CodesResponse::CODE_OK,$centro);

        }catch (\Exception $e){
            return Response::responseError($e->getMessage(),CodesResponse::CODE_INTERNAL_SERVER);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $centro = Centro::query()->findOrFail($id);
        $departamentos = Departamento::query()->orderBy('descripcion')->get();
        $municipios = Municipio::query()->where('departamento_codigo',$centro->departamento_codigo)->get();
        $categoriasPadre = CentrosCategoria::query()->where('categoria_id',null)->get();
        $categoriasHijas = CentrosCategoria::query()->where('categoria_id',$centro->subtipo->categoria_id)->get();
        return view('admin.centros.edit',compact('centro','categoriasPadre','categoriasHijas','departamentos','municipios'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CentroRequest $request, $id)
    {

        try{
            $centro = Centro::query()->findOrFail($id);
            $centro->fill($request->all());
            if(intval($request->departamento_codigo)===8 || intval($request->departamento_codigo)===5){
                $centro->departamento_codigo = '0'.$request->departamento_codigo;
            }
            if($request->has('audio')){

                Storage::delete($centro->audio);
                $centro->audio = null;
                $audio = Storage::put('public',$request->audio);
                $centro->audio = $audio;

            }
            $centro->save();
            return Response::responseSuccess('Bien! El centro se actualizó correctamente',CodesResponse::CODE_OK,$centro);
        }catch (\Exception $e){
            return Response::responseError($e->getMessage(),CodesResponse::CODE_INTERNAL_SERVER);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        try{
            $centro = Centro::findOrFail($id);
            $centro->delete();
            return redirect()->back()->with('success','El centro se eliminó correctamente.');
        }catch (\Exception $e){
            return redirect()->back()->with('error',$e->getMessage());
        }
    }
    public function destroyAudio($id){
        try{
            $centro = Centro::findOrFail($id);
            Storage::delete($centro->audio);
            $centro->audio = null;
            $centro->save();
            return redirect()->back()->with('Se eliminó correctamente el audio');
        }catch (\Exception $e){
            return redirect()->back()->with('error',$e->getMessage());
        }
    }

    public function getSubtipos($tipoId)
    {
        $subtipos = CentrosCategoria::query()->where('categoria_id',$tipoId)->get();
        return $subtipos;
    }
    public function getMunicipios($departamentoId)
    {
        if(intval($departamentoId)===8 || intval($departamentoId)===5){
            $departamentoId = '0'.$departamentoId;
        }
        $subtipos = Municipio::query()->where('departamento_codigo',$departamentoId)->orderBy('descripcion')->get();
        return $subtipos;
    }
    public function indexAliados($centroId)
    {
        $centroNombre = Centro::findOrFail($centroId)->nombre;
        $aliados = Centro::findOrFail($centroId)->aliados;
        return view('admin.centros.aliados', compact('centroId','centroNombre','aliados'));
    }
    public function getAliados($centroId){
       $centro = Centro::query()->findOrFail($centroId);
        $aliados  = Aliado::query()->whereNotIn('id',$centro->aliados->pluck('id'))->get();
      return $aliados;

    }
    public function asociarAliados($centroId,Request $request){
        $centro = Centro::findOrFail($centroId);
        $centro->aliados()->attach($request->aliado_id);
        $validator = Validator::make($request->all(), [
            'aliado_id' => 'required',

        ]);

        if ($validator->fails()) {
            return redirect()->back()->with('error','El campo Aliado es requerido');
        }
        return redirect()->back()->with('success','El aliado se agregó correctamente');
    }
    public function borrarAliados($centroId, $id){
        $centro = Centro::findOrFail($centroId);
        $centro->aliados()->detach($id);
        return redirect()->back()->with('success','El aliado se eliminó correctamente');
    }
}

resources/views/admin/centros/create.blade.php
@extends('admin.layout')

@section('styles')
    <link href="{{asset('plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />
    <link href="{{asset('plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')}}" rel="stylesheet" />
@endsection

@section('contenido')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12 d-flex align-items-center">
                <a href="{{route('centros.index')}}" class="btn btn-primary btn-sm ">
                    <i class="material-icons">arrow_back</i>
                </a>
                <h2 class="pl-3">Crear un centro de ciencia
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('centros.index')}}"><i class="zmdi zmdi-home"></i> Centros</a></li>
                    <li class="breadcrumb-item active">Crear</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix justify-content-center">
            <div class="col col-12 col-md-8">
                <div class="card ">
                    <div class="body">
                        @if(session()->has('success'))
                            <div class="alert alert-success" role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger" role="alert">
                                {{session('error')}}
                            </div>
                        @endif
                            <p class="text-danger">{{$errors->first('nombre')}}</p>
                            <p class="text-danger">{{$errors->first('descripcion')}}</p>
                            <p class="text-danger">{{$errors->first('latitud')}}</p>
                            <p class="text-danger">{{$errors->first('longitud')}}</p>
                        <form id="create-form" >
                            @csrf
                            <div class="form-group">
                                <label for="nombre">Nombre*</label>
                                <input type="text" class="form-control" name="nombre" id="nombre" required>
                            </div>
                            <div class="form-group">
                                <label for="tipo">Tipo*</label>
                                <select class="form-control show-tick" id="tipo" name="tipo" onchange="getSubtipos(this)">
                                    @foreach($categoriasPadre as $cP)
                                        <option value="{{$cP->id}}" >{{$cP->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="subtipo">Subtipo*</label>
                                <select class="form-control show-tick" id="subtipo" name="categoria_id">
                                    @foreach($categoriasHijas as $cH)
                                        <option value="{{$cH->id}}" >{{$cH->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="departamento">Departamento*</label>
                                <select class="form-control show-tick" id="departamento" name="departamento_codigo" onchange="getMunicipios(this)">
                                    <option value="">Selecciona un departamento...</option>
                                    @foreach($departamentos as $departamento)
                                        <option value="{{$departamento->codigo}}" >{{$departamento->descripcion}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="municipios">Municipio*</label>
                                <select class="form-control show-tick" id="municipios" name="municipio_codigo">
                                    <option value="">Selecciona un municipio...</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="owner">Dueño</label>
                                <input type="text" name="owner" class="form-control" id="owner" >
                            </div>
                            <div class="form-group">
                                <label for="descripcion">Descripción</label>
                                <textarea name="descripcion" id="descripcion" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="direccion">Dirección*</label>
                                <input type="text" name="direccion" class="form-control" id="direccion"  required>
                            </div>
                            <div class="row">
                                <div class="col col-12 col-md-6 px-1">
                                    <div class="form-group">
                                        <label for="latitud">Latitud*</label>
                                        <input type="text" name="latitud" class="form-control" id="latitud"  required>
                                    </div>
                                </div>
                                <div class="col col-12 col-md-6 px-1">
                                    <div class="form-group">
                                        <label for="longitud">Longitud*</label>
                                        <input type="text" name="longitud" class="form-control" id="longitud" required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="pagina_web">Página web</label>
                                <input type="text" name="pagina_web" class="form-control" id="pagina_web" >
                            </div>
                            <div class="form-group">
                                <label for="correo">Correo</label>
                                <input type="text" name="correo" class="form-control" id="correo" >
                            </div>
                            <div class="row">
                                <div class="col col-12 col-md-6 px-1">
                                    <div class="form-group">
                                        <label for="telefono">Teléfono</label>
                                        <input type="text" name="telefono" class="form-control" id="telefono" >
                                    </div>
                                </div>
                                <div class="col col-12 col-md-6 px-1">
                                    <div class="form-group">
                                        <label for="celular">Celular</label>
                                        <input type="text" name="celular" class="form-control" id="celular" >
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="fecha_creacion">Fecha de creación</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="zmdi zmdi-calendar"></i>
                                    </span>
                                    <input type="text" name="fecha_creacion" class="form-control " id="date" >
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="audio">Audio</label>
                                <input type="file" accept="audio/*" name="audio" class="form-control" id="audio" >
                            </div>
                            <div class="row justify-content-center">
                                <a href="{{route('centros.index')}}" class="btn btn-secondary">Volver</a>
                                <button type="submit" class="btn btn-primary">Enviar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('plugins/momentjs/moment.js')}}"></script> <!-- Moment Plugin Js -->
    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{asset('plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js')}}"></script>
    <script>

        $(function () {
            $("#create-form").submit(function (e) {
                e.preventDefault();
                var form = $(this);
                var formData = new FormData(form[0]);

                console.log($('#audio').val())
                if($('#audio').val()!="") {
                    formData.append('audio', $('#audio')[0].files[0]);
                }


                console.log(formData.values());

                $.ajax({
                    type: "POST",
                    url: '{{route("centros.store")}}',
                    data: formData,
                    processData : false,
                    contentType : false,
                    beforeSend: function () {
                        cargando();
                    },
                    success: function (result) {
                        cerrarLoader()
                        swal({
                            title:'¡Bien!',
                            text:result.message,
                            type:'success',
                        }).then(()=>{
                            window.location.href = '{{route('centros.index')}}'
                        });

                        form.reset();
                    },
                    error: function (xhr, status) {
                        cerrarLoader()
                        swal({
                            title:'¡Error!',
                            text:xhr.responseJSON,
                            type:'error',
                        })
                    },
                    complete: function (xhr, status) {
                        //fincarga();
                    }
                });

            });


        })
        $('#date').bootstrapMaterialDatePicker({ weekStart : 0, time: false, lang:'es'});

        function getSubtipos(select) {
            var tipoId = $(select).val()
            $.get('/centros/subtipos/'+tipoId, function (resp) {
                $("#subtipo").empty()

                for(var i=0; i<resp.length; i++){
                    $("#subtipo").append(`<option value="${resp[i].id}">${resp[i].nombre}</option>`)
                }

                $('#subtipo').selectpicker('refresh');

            })
        }
        function getMunicipios(select) {
            var departamentoId = $(select).val()
            if(departamentoId === '' || departamentoId=== null) {
                $("#municipios").empty()
                $("#municipios").append(`<option value="">Selecciona un municipio...</option>`)
                $('#municipios').selectpicker('refresh');
            }else {
                $.get('/centros/departamentos/' + departamentoId, function (resp) {
                    $("#municipios").empty()

                    for (var i = 0; i < resp.length; i++) {
                        $("#municipios").append(`<option value="${resp[i].codigo}">${resp[i].descripcion}</option>`)
                    }

                    $('#municipios').selectpicker('refresh');

                })
            }
        }

    </script>
@endsection

resources/views/admin/centros/index.blade.php
@extends('admin.layout')

@section('styles')
    <link rel="stylesheet" href="{{asset('plugins/jquery-datatable/dataTables.bootstrap4.min.css')}}">
@endsection

@section('contenido')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Centros de Ciencia
                    <small>Listado de los centros de ciencia en Colombia</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('centros.index')}}}"><i class="zmdi zmdi-home"></i> Centros</a></li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12">
                <div class="card ">
                    <div class="body table-responsive">
                        @if(session()->has('success'))
                            <div class="alert alert-success" role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger" role="alert">
                                {{session('error')}}
                            </div>
                        @endif
                            <div class = "row justify-content-end">
                                <a href="{{route('centros.create')}}" class="btn btn-primary btn-sm ">
                                    <i class="material-icons">add_circle</i>
                                    <span style="vertical-align: top" class="d-inline-block pt-1">Agregar Centro</span>
                                </a></div>

                            <table class="table table-hover table-striped table-borderless m-b-0" id="table-centros">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Tipo</th>
                                <th>Subtipo</th>
                                <th>Departamento</th>
                                <th>Municipio</th>
                                <th>Dirección</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody class="no-border-x">
                            @foreach($centros as $centro)
                                <tr>
                                    <td>{{$centro->id}}</td>
                                    <td>{{$centro->nombre}}</td>
                                    <td>{{$centro->subtipo->padre->nombre}}</td>
                                    <td>{{$centro->subtipo->nombre}}</td>
                                    <td>{{$centro->departamento->descripcion}}</td>
                                    <td>{{$centro->municipio->descripcion}}</td>
                                    <td>{{$centro->direccion}}</td>
                                    <td>
                                        <div class="btn-group btn-group-sm" role="group" >
                                        <a href="{{route('centros.edit',$centro->id)}}" data-toggle="tooltip"  title="editar" class="btn btn-primary btn-sm">
                                            <i class="material-icons">edit</i>
                                        </a>
                                        <a href="{{route('entradas.index',$centro->id)}}"  data-toggle="tooltip" title="entradas" class="btn btn-primary btn-sm">
                                            <i class="material-icons">directions_run</i>
                                        </a>
                                        <a href="{{route('servicios.index',$centro->id)}}" data-toggle="tooltip"  title="oferta general" class="btn btn-primary btn-sm">
                                            <i class="material-icons">assignment</i>
                                        </a>
                                            <a href="{{route('proyectos.index',$centro->id)}}" data-toggle="tooltip"  title="proyectos" class="btn btn-primary btn-sm">
                                                <i class="material-icons">folder</i>
                                            </a>
                                        <a href="{{route('centros.aliados',$centro->id)}}"  data-toggle="tooltip"  title="aliados" class="btn btn-primary btn-sm">
                                            <i class="material-icons">contacts</i>
                                        </a>
                                        <a href="{{route('horarios.index',$centro->id)}}"  data-toggle="tooltip"  title="horarios" class="btn btn-primary btn-sm">
                                            <i class="material-icons">schedule</i>
                                        </a>
                                            <a href="{{route('imagenes.index',$centro->id)}}" data-toggle="tooltip"  title="imagenes" class="btn btn-primary btn-sm">
                                                <i class="material-icons">burst_mode</i>
                                            </a>



                                            <button class="btn btn-danger btn-sm"  data-toggle="tooltip"  title="eliminar" onclick="eliminarEntrada('{{$centro->id}}')"><i class="material-icons">delete</i></button>
                                        <form id="form-entrada-{{$centro->id}}"  method="post" action="{{route('centros.destroy',$centro->id)}}">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('bundles/datatablescripts.bundle.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.html5.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-datatable/buttons/buttons.print.min.js')}}"></script>
    <script>
        $(function () {
            $('#table-centros').DataTable();
            $('[data-toggle="tooltip"]').tooltip()
        });
        function eliminarEntrada(id) {
            swal({
                title:'¿Estás seguro?',
                text:'¿Deseas eliminar este centro?',
                type:'warning',
                showCancelButton: true,
                cancelButtonText:
                    'Cancelar',
            }).then(()=>{
                $("#form-entrada-"+id).trigger('submit')
            });
        }
    </script>
@endsection